# Generated by Django 4.1.1 on 2022-09-15 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='zsipcode',
            new_name='zipcode',
        ),
    ]
